resilience4j:
  retry:
    instances:
      passengerService:
        maxRetryAttempts: 10
        waitDuration: 1s
server:
  port: 8081

spring:
  application:
    name: USER-SERVICE
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost